global:
  scrape_interval: 15s

scrape_configs:
  - job_name: spring-actuator
    metrics_path: /actuator/prometheus
    scrape_timeout: 10s
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
        - bn-container:8095
        - bn-redis-container:8096
        - db-container:8097
        - fn-container:8098

  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus-container:9090
