name: Upload Images

on:
  workflow_dispatch:
    inputs:
      files:
        description: 'Comma-separated list of file names'
        required: true
      file_contents:
        description: 'Comma-separated list of base64 encoded file contents'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upload images
        run: |
          # Convert the comma-separated file names and contents into arrays
          IFS=',' read -r -a file_names <<< "${{ github.event.inputs.files }}"
          IFS=',' read -r -a file_contents <<< "${{ github.event.inputs.file_contents }}"

          # Create a directory for uploads if it doesn't exist
          mkdir -p images/uploads

          # Loop through the files and create them
          for i in "${!file_names[@]}"; do
            echo "${file_contents[$i]}" | base64 --decode > "images/uploads/${file_names[$i]}"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "jwg8910@naver.com"
          git config --local user.name "jungwoogyun"
          git add images/uploads/*
          git commit -m "Upload images"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
