name: Upload Images

on:
  workflow_dispatch:
    inputs:
      files:
        description: 'Comma-separated list of file names to upload'
        required: true
        default: ''

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Upload images
        run: |
          # Convert the comma-separated file names into an array
          IFS=',' read -r -a files <<< "${{ github.event.inputs.files }}"

          # Create a directory for uploads if it doesn't exist
          mkdir -p uploads

          # Loop through each file and download it
          for file in "${files[@]}"; do
            # Here you would typically download the file from a source
            # For demonstration, we will just create a dummy file
            echo "This is a dummy file for $file" > "uploads/$file"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "jwg8910@naver.com"
          git config --local user.name "jungwoogyun"
          git add uploads/
          git commit -m "Upload images: ${{ github.event.inputs.files }}"
          git push
