name: Upload Files to Public Repo

on:
  workflow_dispatch:
    inputs:
      files:
        description: "Paths of files to upload"
        required: true

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      # 1. 대상 저장소 클론
      - name: Clone target repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://${{ secrets.TARGET_REPO_PAT }}@github.com/ALL-MY-PROJECTS-2025/CALENDAR_PHOTO_SAVE.git

      # 2. 파일 복사
      - name: Copy uploaded files
        run: |
          echo "${{ github.event.inputs.files }}" | tr ',' '\n' > file-list.txt
          while read file; do
            cp "$file" ./target-repo/
          done < file-list.txt

      # 3. Push 변경 사항
      - name: Push files to target repository
        run: |
          cd target-repo
          git add .
<<<<<<< HEAD
          git commit -m "Uploaded images via GitHub Actions"
=======
          git commit -m "Upload images via GitHub Actions"

      # 4. Push 변경 사항
      - name: Push to target repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions에서 기본 제공
        run: |
          cd target-repo
>>>>>>> 86e7bbe518e5ab7b9154a6e9c34f5ec0ff16b40e
          git push
